name: Cypress tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress.io
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          build: yarn build
          start: serve -s build
          wait-on: 'http://localhost:5000'
          config: baseUrl=https://localhost:5000
